---
- name: A Playbook to configure the Crowdstrike sensor
  hosts: caesar.thenorvilles.com
  gather_facts: true
  become: true
  vars_files: 
    - falcon_vars.yml    

  roles:

    - role: crowdstrike.falcon.falcon_configure
      vars:
        falcon_cid: 5201BB84EA4E42EFABECCF130C14CA37-6B